### ISSUE TITLE
SoapySDR readStream failed: OVERFLOW

### ISSUE THREAD

**Issue by dupilax** [pothosware/SoapyAirspyHF#11]
Hello

Since this morning I got this annoying error message : SoapySDR device 'driver=airspyhf,device_id=0': readStream failed: OVERFLOW, disabling

Every component (SoapySDR, SoapyAirspyHF, firmware of the Airspy HF) is up-to-date and I can't get rid of this error...

Any idea to solve this ?

Thanks

**Comment by guruofquality** [comment]
Overflows may be normal, especially if the application has not read from the stream buffer fast enough. 

Since the application is printing `readStream failed: OVERFLOW, disabling`, what does that mean? Does "disabling" mean that it stops processing the stream? If you force the application to continue reading the stream does it recover? Perhaps its just a one time issue during setup when samples build up in the buffer before the application can read them out.

**Comment by dupilax** [comment]
dev of rtl_airband says is it not possible because it could lead to unpredictable behavior.

I upgrade the Raspbian kernel two days before SoapySDR, could it be the root cause ?

**Comment by dupilax** [comment]
it was an Airspyhf library problem.
the dev change one parameter from airpsy.c from #define SAMPLES_TO_TRANSFER (1024 * 16) to #define SAMPLES_TO_TRANSFER (1024 * 2)

if I compile airspyhf lib #define SAMPLES_TO_TRANSFER (1024 * 16) no more problem !

Thanks

**Comment by guruofquality** [comment]
If they have a hook to control this parameter in the API, this is actually what the stream args in setupStream are supposed to be used for. So we can change it at runtime based on use cases :-)
